### PR TITLE
changing input_spec to allow tasks without input

### PR DESCRIPTION
**Pull request by djarecka**
tasks without inputs didn't work

### CODE REVIEW

**Comment by satra** [comment]
i'm inclined not to support this. can you think of a situation in a dataflow for a task not to have an input?

**Comment by djarecka** [comment]
@satra - as you want. I noticed this when I worked on notebooks and I thought that we should allow it, but no strong feelings...

**Comment by satra** [comment]
leave this as an orphaned PR, but i would prefer not.

**Comment by djarecka** [comment]
@satra - and what if we specify input for task, and not for wf? 

```
wf1 = pydra.Workflow(name="wf1")
wf1.add(add_two(name="add_two", x=1))
```

**Comment by satra** [comment]
> and what if we specify input for task, and not for wf?

a `Workflow` is a `Task` hence has to have the same consideration. i.e. there has to be at least one task that receives a workflow input

**Comment by djarecka** [comment]
ok

**Pull request closed without merging**
