### PR TITLE
Raise error when task or workflow name conflicts with names of attributes/methods/other tasks added to workflow

### PR DESCRIPTION
**Pull request by nicolocin**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

Fix for #250 

## Checklist

- [x] All tests passing
- [x] I have added tests to cover my changes
- [] I have updated documentation (if necessary)
- [x] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by djarecka** [comment]
@satra - I would say, that even if we want to add the same function to a workflow it should have a different name

**Comment by satra** [comment]
>  if we want to add the same function to a workflow it should have a different name

that's what this PR would achieve, but i think the overwriting of prior task values would still hold. i.e. adding the same task with a new name can change the settings of a previously added task.

**Comment by satra** [comment]
let me check something about init and TaskBase

**Comment by satra** [comment]
nevermind, when initializing a task it creates new objects, so this will not be an issue:

```
In [6]: fftt = task(annotate({"return": {"out": ty.Any}})(np.fft.fft)) 

In [11]: t1 = fftt(name="1", a=[1,4])                                                     
In [13]: t2 = fftt(name="2", a=[1,1])                                                     
In [19]: t1.inputs                                                                        
Out[19]: Inputs(a=[1, 4], n=None, axis=-1, norm=None, _func=b'\x80\x04\x95\x15\x00\x00\x00\x00\x00\x00\x00\x8c\tnumpy.fft\x94\x8c\x03fft\x94\x93\x94.')
```

**Pull request merged**
