### PR TITLE
Testing for windows on Azure Pipelines and Travis

### PR DESCRIPTION
**Pull request by nicolocin**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

Adding windows CI on Azure Pipelines and travis.  So far testing on Python 3.7 on x64 and x86 of windows 10, but more can be added as necessary.   Thanks a lot to @djarecka for some windows bug fixes and Travis support!

## Checklist

- [x] All tests passing
- [x] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [x] My code follows the code style of this project 
(we are using `black`: you can `pip install pre-commit`, 
run `pre-commit install` in the `pydra` directory 
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by nicolocin** [comment]
https://dev.azure.com/lokyeenicol/pydra/_build

@satra - after @djarecka added windows on Travis we thought about ditching Azure entirely, but I noticed that some tests were still failing on my win10 and Azure when Travis was passing.   Figured it nice to have.

Managed to generate `cov.xml` in Azure but haven't figured out how to upload it to codecov yet.  Looking into it

**Comment by djarecka** [comment]
@nicolocin - thanks! I don't see azure running here, you still perhaps have to allow azure to run on this repo. 

also circleCI complains about the docs - not sure if this is the reason but looks like you added a new notebook, that I'm not sure was supposed to be a part of this repo

**Comment by nicolocin** [comment]
Ohhh ok sorry forgot to set up Azure on the nipype repo.  Just requested organization access.  I thought the tutorial commit was on another branch, I'll delete it thanks for letting me know.

I integrated changes from `nipype/master` to this branch earlier, and CircleCI is complaining about the changes in the last `gh-pages` pull request (which was skipped by CircleCI).  See error below.  Any suggestions what to do?

`Warning, treated as error:
/tmp/gh-pages/pydra/engine/state.py:docstring of pydra.engine.state.State.combiner:1:duplicate object description of pydra.engine.state.State.combiner, other instance in api/pydra.engine.state, use :noindex: for one of them
make: *** [Makefile:59: html] Error 2
make: Leaving directory '/tmp/gh-pages/docs'

Exited with code exit status 2`

**Comment by djarecka** [comment]
the documentation was fixed in #235, so you should merge master again

azure is approved, so should work now

**Comment by nicolocin** [comment]
Merged master!   Somehow azure still needs to be approved at nipype?  It also can't recognize new files that are added in pull requests, so I think it might only start to run once the pull request is merged?

How can I make the codecov/project check successful?  Haven't used it before not too sure how it works.  Thanks!

Azure Setup Screenshot

**Comment by djarecka** [comment]
@nicolocin - you should be able to manage the access to the repository on you own, added you as an admin

**Comment by djarecka** [comment]
@nicolocin - I've seen that you merged it already, but I still don't see azure report... Also we should figure out the coverage. If you don't want t do it in this PR, please open an issue

**Comment by djarecka** [comment]
I actually can see azure running for master, great! :-)

Could you just double check if you enabled it for PRs?

**Comment by nicolocin** [comment]
@djarecka - Thanks!  Also I think codecov is mostly complaining about `pydra/engine/task.py` which I didn't change; the edits are from the merge so I have no clue what's going on there.  

Azure should be enabled for new PRs :)

**Comment by djarecka** [comment]
@nicolocin -codecov is not 100% reliable, so don't worry about complains, I just wanted to be sure that we remember about adding codecov to the azure pipeline

**Comment by djarecka** [comment]
@nicolocin - you should add your name to the zenodo file, but you have to create your orcid if you don't have one yet

**Pull request merged**
