### PR TITLE
Removing newinterface

### PR DESCRIPTION
**Pull request by djarecka**
(edited)
- [x]  removing new interfaces and using `CurrentInterface` for all functions and tests

- [x] some cleaning of results syntax

- [x] fixing `checking_output` (checking if `result_*.pklz` is not empty)

### CODE REVIEW

**Comment by effigies** [comment]
Please tag this with whether you want to get this in for the initial release (0.0.1) or 0.1.0. Even if it's 0.1.0, if it's ready to merge before 0.0.1 is closed, we can still do it.

**Comment by djarecka** [comment]
@effigies - would prefer to add it to 0.0.1. Trying to change one more thing, but can finish soon without  changing all pieces

**Comment by djarecka** [comment]
@effigies - ok, I will rebase it with master and will finish this PR. Other changes will add to the join/combine PR

**Comment by djarecka** [comment]
@effigies - codecov/patch  doesn't like this PR, but I'd merge it for now anyway...

**Comment by effigies** [comment]
Given tests pass, I'm merging. I've only cursorily reviewed this.

**Pull request merged**
