### PR TITLE
Fix DaskWorker: `AttributeError: 'tuple' object has no attribute '_run'`

### PR DESCRIPTION
**Pull request by adi611**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
 
## Summary

This is a fix to DaskWorker which previously failed on some tests with the following error: `AttributeError: 'tuple' object has no attribute '_run'`. (Refer discussion #665).

## Checklist

- [ ] I have added tests to cover my changes (if necessary)
- [ ] I have updated documentation (if necessary)

### CODE REVIEW

**Comment by djarecka** [comment]
@adi611 - thank you for this change, but I understand that dask is still not tested in CI, so we should add it and fix the tests

**Comment by djarecka** [comment]
we still have to understand why this specific test is failing

**Comment by adi611** [comment]
The tests `test_duplicate_input_on_split_wf` and `test_inner_outer_wf_duplicate` in `test_workflow.py` are failing after reaching the timeout for Python versions `3.9` and `3.10`. They also fail for Python version `3.8`, but as it is an older version, I am currently disregarding it. These tests are not Dask tests; instead, they run on the `cf` plugin. It seems to be a GA specific issue since the tests run successfully locally and on Google Colab. Please let me know if I should consider increasing the timeout limit for these tests or if there are any other possible solutions.

This also indicates that all the Dask tests pass for Python versions `3.9` and `3.10`.

**Comment by djarecka** [comment]
for some reason i'm having problems with seeing reports from the tests right now..:( What do you mean this tests are not dask tests, I'm guessing that since it only happens with the "dask" run, some tests are stuck when running the dask plugin, am I right?

Do they have a reasonable running time on google collab?

**Comment by adi611** [comment]
Sorry for the confusion. The tests `test_duplicate_input_on_split_wf` and `test_inner_outer_wf_duplicate` in `test_workflow.py` are the only failing tests for Python `3.9` and `3.10`. These tests run on `cf` only, using `plugin="cf"`. The tests which run on both `dask` and `cf` have `plugin=plugin_dask_opt` which is not the case here. So what I meant was the reason these tests are failing may not be a dask related one.

Moreover these tests are passing on Google Colab, as can be seen here: [github gist for python 3.10](https://colab.research.google.com/gist/adi611/f0c6689a1e538ef5587b5e04a63d5178/untitled16.ipynb), [github gist for python 3.9](https://colab.research.google.com/gist/adi611/0695067a7ed043b4ca22fcc8bd1008b2/untitled17.ipynb).

**Comment by djarecka** [comment]
@adi611 - it looks like the change in timeout didn't help, and I actually check one of the GA report (for 3.9), and I can see that there is an issue with another test, with `test_wf_3nd_st_1` that doesn't have timeout, but it fails (even with rerun). It also fails on my laptop... 

Are you really able to run without any issues this test locally?

**Comment by adi611** [comment]
@djarecka - The test `test_wf_3nd_st_1` was not failing before increasing the timeout. In fact, for my fork of the repo the tests actually pass for Python `3.9`, and while they do fail for Python `3.10` , it is only for the tests `test_duplicate_input_on_split_wf` and `test_inner_outer_wf_duplicate`. It can be seen [here](https://github.com/adi611/pydra/actions/runs/5577146618/job/15657744300).

Even though the results appear to be inconsistent across platforms, running the test files individually does not result to any error in any platform. I have created a new GA workflow to verify the same. This will be helpful in understanding the cause of the problem.

**Comment by djarecka** [comment]
ok, thank you. I've approved the workflows, so should run now

**Comment by ghisvail** [comment]
Superseded by #686

**Pull request closed without merging**
