### PR TITLE
ENH: Use Python's ``hash`` built-in to calculate checksums

### LINKED ISSUE #167: Use Python's __hash__ whenever possible
Dataclasses define a `__hash__` member (when the appropriate arguments are given in the decorator). We could/should use the `hash()` built-in to check hashes, instead of:

https://github.com/nipype/pydra/blob/51fdbbf27aebbd9c78b9726098804015701fa198/pydra/engine/specs.py#L40-L59

The whole method could go away, defining the proper `__hash__` in File:

https://github.com/nipype/pydra/blob/51fdbbf27aebbd9c78b9726098804015701fa198/pydra/engine/specs.py#L11-L12

And make sure we set `compare` or `hash` to `False` in the appropriate fields that should not be considered for comparison and/or hashing.

There is that last exception of ``field.name not in ["_graph_checksums", "bindings"]`` - I'm not sure if a field can dynamically change their `compare` or `hash` when they are added to `bindings`. For `_graph_checksums` then the `__hash__` member of the field should be mutated (if I understood correctly the property).

Any reason not to try to stick with the `hash` built-in? I believe that has been a source of unreliability in Nipype 1.0 (I can remember it was particularly painful during the migration to unicode strings).

### PR DESCRIPTION
**Pull request by oesteban**
Closes #167

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project 
(we are using `black`: you can `pip install pre-commit`, 
run `pre-commit install` in the `pydra` directory 
and `black` will be run automatically with each commit)

## Acknowledgment
- [ ] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by oesteban** [comment]
@satra, haven't you hit https://bugs.python.org/issue24132 when using our `File` derived from `pathlib.Path`?

**Comment by effigies** [comment]
If I'm not mistaken, the main effect of defining __hash__ is to make this object insertable into a dictionary or set. My feeling is that this is a pretty drastic reinterpretation of the API, and one that could have unintended consequences.

**Comment by satra** [comment]
i haven't hit the bug. 

i also wouldn't override the built in hash. that function is created for immutable objects, and in this case one can assign a new value to that variable at any time. the built in hash function has some specific requirements for python, and there is no advantage gained i think by overriding it in this case.

**Comment by anibalsolon** [comment]
The applicability scenario in Pydra of redefining the __hash__ function using hashlib and similar would be for multi-process executions. The native hash function has a nondeterministic behavior (by default in python >= 3.3) across processes, so hashes will not match if comparing in one process file hashes generated in another process.

https://docs.python.org/3.3/reference/datamodel.html#object.__hash__

**Comment by oesteban** [comment]
Thanks for the feedback, this doesn't seem like a good idea.

**Pull request closed without merging**
