### PR TITLE
Initial attempt at adding infile tracking

### PR DESCRIPTION
**Pull request by rcali21**
Adding infile tracking for BIDS-PROV.

### CODE REVIEW

**Comment by rcali21** [comment]
WIP-Adding complimentary test.

**Comment by djarecka** [comment]
@rcali21 - thanks for opening this, but remember that a task could use various files (or directories) as an input, not all would be called `in_file`

**Comment by rcali21** [comment]
> @rcali21 - thanks for opening this, but remember that a task could use various files (or directories) as an input, not all would be called `in_file`

Hi Dorota,

Yes, I remember you and I discussing this. This was more of a placeholder for now. Am I remembering correctly that you wanted this to just be a UUID, or was it something else entirely?

**Comment by rcali21** [comment]
> not sure if I understand correctly, `uuid` of the `Input` entity will be used in the `Used` field of the `Activity` (i.e. task), but you have to create a completely new `Input` entity that has several fields.

Yeah, I think I was misunderstanding it then. So "Used" should be implemented after "Entity" is implemented. I can rename the PR to focus on that.

**Comment by djarecka** [comment]
correct, start from `Input` entity, similarly `Output` will be a separate entity

**Pull request closed without merging**
