### PR TITLE
using asyncio.SelectorEventLoop() to get a loop

### PR DESCRIPTION
**Pull request by djarecka**
## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

I was getting error from `asyncio.get_event_loop()` when pydra was run after `datalad` (also uses `asyncio`).

## Checklist

- [x] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [x] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

### CODE REVIEW

**Comment by mgxd** [comment]
Hey @djarecka, what specific error were you getting? Do you have a minimal reproducible example?

**Comment by djarecka** [comment]
@mgxd - here you have description: https://github.com/datalad/datalad/issues/5313

haven't checked yet if python 3.8 solves it

Do you remember why you used `Selectors` only for windows?

**Comment by mgxd** [comment]
I believe at the time the default loop was only `SelectorEventLoop`, so wanted to ensure Windows was getting the correct implementation. Though it seems asyncio's defaults should handle this fine in at least 3.9

https://docs.python.org/3/library/asyncio-eventloop.html#event-loop-implementations

**Comment by djarecka** [comment]
I haven't removed the check for the OS, still using `ProactorEventLoop` for windows

**Comment by djarecka** [comment]
at the end I decided to bring back `get_event_loop`, but just added `try/except` block and in case of error I just use `new_event_loop` instead of using selector directly.

**Pull request merged**
