### PR TITLE
[WIP] STY: Flake8 cleanup

### PR DESCRIPTION
**Pull request by effigies**
This is purely a style cleanup. No refactors or changes in functionality are being proposed.

First step for #10.

### CODE REVIEW

**Comment by effigies** [comment]
This is going to break all other PRs. @oesteban if you want to get yours in first, that's fine with me.

**Comment by rmarkello** [comment]
Thoughts on adding `flake8` to the test suite as a requirement for new contributions? As you said, would be good to start off on the right foot!

**Comment by effigies** [comment]
@rmarkello Yup, that would be great, but figured we should fix the issues first.

**Comment by satra** [comment]
should we just ask folks to use `yapf`, like we do for nipype?

**Comment by effigies** [comment]
Closed in favor of #15.

**Pull request closed without merging**
