### PR TITLE
tests for docker task

### PR DESCRIPTION
**Pull request by djarecka**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary
- adding tests for DockerTasks: tasks, tasks with State, tasks in wf

decided to not fix some of the issues for now, but created #141 
## Checklist

- [x] All tests passing
- [x] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [x] My code follows the code style of this project 
(we are using `black`: you can `pip install pre-commit`, 
run `pre-commit install` in the `pydra` directory 
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by satra** [comment]
lgtm - any idea why coverage is decreasing?

**Comment by djarecka** [comment]
@satra - it annoyed me too and I was checking it earlier. Not completely sure, but IMO what you see here might be not updated, since when go to codecov and see the report, it looks like this:
https://codecov.io/gh/nipype/pydra/pull/142

I'm guessing that codecov decreased the the coverage at the beginning because slurm travis was failing. 

It's still a bit mystery to me, since only some new tests were failing for slurm, but this is the best explanations I could think about.

Don't also know why it's not updating.

**Comment by djarecka** [comment]
exactly the same tests give different coverage report here:
https://github.com/nipype/pydra/pull/143

**Comment by djarecka** [comment]
was hoping that after merge the codecov will use a newer report, but no... it will have to wait for another PR

**Pull request merged**
