### PR TITLE
checksum_states improvements

### PR DESCRIPTION
**Pull request by djarecka**
## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

- improving `checksum_states` so it doesn't have to calculate the content hash of big files for every single element of the task state (function used in `result`), using `files_hash` that keeps track of all the files for the task (combining files from different state elements)

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

### CODE REVIEW

**Comment by satra** [comment]
i do think this is where you would use a separate LRU cache, so you can reuse hashes across tasks. so i would recommend implementing a more general solution to this.

**Comment by djarecka** [comment]
so you want to save hashes in files?

**Comment by satra** [comment]
easiest may indeed be a single "database" file in the cache directory that can be protected against concurrent writes by softlock. but would be harder to maintain an LRU cache since items would need to be shuffled.

the alternative would be to create a BaseSpec class attribute that is set before anything is initialized. i don't know the implications for pickling, how to achieve concurrent/async updates etc.,. but i suspect this must have been looked at by people in the community.

```
class LRUwrapper:
    cache = None
    def __repr__(self):
         return str(cache)

class BaseSpec:
     filecache = LRUwrapper()
```

**Comment by djarecka** [comment]
it depends how many things we want to fix with this PR. The part I was addressing here is run by the main node.

**Comment by satra** [comment]
@djarecka - it's fine for this PR to fix the present issue, but i would suggest at least filing an issue for improving hashing efficiency

**Review by satra — APPROVED** [review]

**Comment by djarecka** [comment]
@satra - oh, ok. I was double checking this on openmind first and was planning to try to follow your suggestion, but it might be better in a new PR that modifies all places that use hash. will open an issue

**Pull request merged**
