### PR TITLE
fixing the memory issue for workflows with a big splitters (closes #371)

### LINKED ISSUE #371: big memory use for workflows
The problem was originally reported by @Hoda1394 and I'm currently testing suing this kind of workflows:

```
@mark.task
def show_var(a):
    return a

def generate_list(l):
    my_list = np.arange(l).tolist()
    return my_list

wf= Workflow(name="wf", input_spec=["x"])
wf.split("x", x=generate_list(size))
wf.add(show_var(name="show", a=wf.lzin.x))
wf.set_output([("out", wf.show.lzout.out)])
wf()
```

So I do see a non-linear (quadratic?) relation between memory and the size of the list. I decided to rely mostly on the RSS memory measure from GNU time, and here is a plot:
rss_wf

This is a workflow related issue, I've tested tasks with a splitter and the relation is linear.

I've been struggling to debug it, but I got to a point that I think I know where the problem is generated, but not sure why. It could be also that I'm simply missing something else. I've modified `submit` method to add a simple print statement (wrapped in a coroutine) to `futures` instead of `worker.run_el` (see [here](https://github.com/djarecka/pydra/blob/tmp_testmem_2.1/pydra/engine/submitter.py#L137)) and this single modified line still leads to increase the memory. Any thoughts? (cc:@satra, @mgxd )

### PR DESCRIPTION
**Pull request by djarecka**
## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

- removing state_inputs from  Task class (was not used anymore), 
- fixing issues for workflow with a big splitter 
- adding tests to check the memory object together with pympler library 

## Checklist

- [x] All tests passing
- [x] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [x] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

### CODE REVIEW

**Comment by djarecka** [comment]
@satra - not sure how I missed this earlier, but it was just about the task that are loaded, we were resetting state and inputs, but not `state_inputs` that was just a remainder of one of the old versions

**Comment by satra** [comment]
if it's that simple, that's great.

**Comment by djarecka** [comment]
@satra - it came from the `futures` set, but python/asyncio are responsible for the linear relation, the quadratic part was in the task part itself...

**Comment by djarecka** [comment]
@satra - are you ok with adding additional library to the test installation? I think this simple test could be pretty useful

**Comment by satra** [comment]
yes a testing library is fine for now. we need to refactor test dependencies anyway.

**Comment by djarecka** [comment]
ok, added an additional test, once it passes I will merge it

**Pull request merged**
