### PR TITLE
fixing __call__ function

### PR DESCRIPTION
**Pull request by djarecka**
## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

fixing `__call__` function, so the `submitter` is not overwritten when state

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

### CODE REVIEW

**Comment by satra** [comment]
i know this fixes the current issue, but perhaps we could extend the plugin support a bit. we could add `plugin_kwargs` to the call signature and to wherever we set `self.plugin`

```
def __cal__(..., plugin_kwargs={}, **kwargs):
    ...
    plugin_kwargs = plugin_kwargs or self.plugin_kwargs
    if submitter is None:
        submitter = Submitter(plugin=plugin or 'cf', **plugin_kwargs)
    ...
```

**Comment by djarecka** [comment]
for some reason, we didn't always want to create a new submitter, if nothing is provided... but will check it

**Comment by satra** [comment]
i didn't pay attention to the full logic, so this should be better.

```
if submitter is None and self.state or plugin:
```

**Comment by djarecka** [comment]
I actually want to revisit why we raise an error [here](https://github.com/nipype/pydra/pull/388/files#diff-3b85fb775d1f906f1a06277170afbaa573e7fc2c4701d138e79efe7fef229bc5L412), can't really remember why we don't handle this

**Comment by djarecka** [comment]
@satra - are you ok with merging this?

**Pull request merged**
