### PR TITLE
fix: new location for prov context

### PR DESCRIPTION
**Pull request by satra**
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary
original prov context is not available.

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

## Acknowledgment
- [X] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
Do we need to consider versioning our context file? And is there any consequence to this change for a consumer? Would it recognize the new version as the same as the old, or can we add some kind of assertion saying the object referenced by the new URI is the same as the old URI?

**Comment by satra** [comment]
the consumer shouldn't need to change since we are changing this in the master for now. the other thing we can do is to include the contents of the versioned url into this context. 

in terms of versioning the context, we can consider it but not for the moment. it's fairly lightweight and till we formalize the prov pieces (including BEP028 and nidm-workflows), i would keep this in draft state. we should be careful not to remove things (which would cause some backward compatibility issues), but adding things should not be a problem.

**Comment by effigies** [comment]
Okay. The new location looks like it's as stable as ours, so I wouldn't insist on including its contents.

LGTM.

**Comment by djarecka** [comment]
since the original link works now, maybe we shouldn't merge it

**Comment by satra** [comment]
this is still a more persistent link - so moving to this is better relative to the original link.

**Comment by djarecka** [comment]
@satra - I'm still afraid that something else was also causing this error yesterday, but we can worry if it returns

**Pull request merged**
