### PR TITLE
CI: Check minimum dependencies

### PR DESCRIPTION
**Pull request by effigies**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary
Adds a CI entry to check that our listed minimum dependencies are accurate. Using a `min-requirements.txt` to keep the number of places to check minimal, though open to alternatives.

## Checklist

- [x] All tests passing
- [x] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [x] My code follows the code style of this project 
(we are using `black`: you can `pip install pre-commit`, 
run `pre-commit install` in the `pydra` directory 
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by satra** [comment]
would the pre-option still check other versions?

**Comment by effigies** [comment]
Interpreting that as "Does the `PIP_ARGS=--pre` entry still check new versions?". If that's the question, yes, though I'll check the outputs to be sure.

**Comment by effigies** [comment]
Looks like it, though there aren't pre-releases of either of our two dependencies right now. Except on this new entry, we install cloudpickle 1.2.1 and filelock 3.0.12.

The [failing test](https://travis-ci.org/nipype/pydra/jobs/565008427) is #90. I don't know if there's anything interesting to be divined from those logs, though...

**Comment by effigies** [comment]
RE filelock, I don't have a good reason for picking [3.0.0](https://github.com/benediktschmitt/py-filelock/releases/tag/v3.0.0), except it's older than both pydra and the filelock docs.

As to going with more recent release, I don't see any critical failures being reported (looking through issues and PRs) in this window, so it's not obvious we need to be more restrictive.

Could be less restrictive, but not clear how much benefit there is to finding the absolute oldest version that does what we need.

In any case, I think it's a good idea to put a minimum version in the `install_requires` before merge. I was also thinking of writing a quick script to synchronize `min-requirements.txt` from `setup.cfg`.

**Pull request merged**
