### PR TITLE
WIP: few minor edits

### PR DESCRIPTION
**Pull request by zswgzx**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [x] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by zswgzx** [comment]
comments welcomed

**Comment by satra** [comment]
@zswgzx - thank you, but before you do too much, for pydra we will use the numpydoc style for a lot of docstrings: https://numpydoc.readthedocs.io/en/latest/format.html

if you are using something like pycharm you can set this using Preferences/Settings->Tools->Python Integrated Tools->Docstring Format

this hasn't been consistent, but let's do this from here on out.

**Comment by zswgzx** [comment]
updated

**Comment by djarecka** [comment]
@zswgzx - thank you! Some tests are failing, do you want to check it. Have you tried to run tests locally using pytest?

**Comment by zswgzx** [comment]
> @zswgzx - thank you! Some tests are failing, do you want to check it. Have you tried to run tests locally using pytest?

1. not sure why windows related ci failed... but glad to help if needed
2. no, haven't tried unit test with pytest. Any clue about what to do w/ pytest for the task above in 1.?

**Comment by djarecka** [comment]
I think the tests are failing for all OS in this PR. I can help you with debugging, but if you wanna try to see what is wrong you should run pytest locally, I've just updated the [readme](https://github.com/nipype/pydra/blob/master/README.md#developer-installation).

**Comment by zswgzx** [comment]
> I think the tests are failing for all OS in this PR. I can help you with debugging, but if you wanna try to see what is wrong you should run pytest locally, I've just updated the [readme](https://github.com/nipype/pydra/blob/master/README.md#developer-installation).

sure let me take a look first

**Comment by effigies** [comment]
This needs to be redone on a recent master, if it's still worth doing.

**Pull request closed without merging**
