### PR TITLE
[ci] adding python 3.9 for GA

### PR DESCRIPTION
**Pull request by djarecka**
## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

### CODE REVIEW

**Comment by djarecka** [comment]
@satra i had [issues with numpy](https://github.com/numpy/numpy/issues/17569#issuecomment-736852608), but perhaps it works now

**Comment by effigies** [comment]
Yes, numpy has published wheels, so there is no need for users to compile it themselves.

**Comment by azizur** [comment]
I am still getting the following error.
> ERROR: Failed building wheel for numpy
> Failed to build numpy
> ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly

**Comment by effigies** [comment]
Hi @azizur, can you provide information on the system you're trying to install on and your Python version?

**Pull request merged**
