### PR TITLE
fixing issues with numpy arrays provided as an input

### PR DESCRIPTION
**Pull request by djarecka**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

The current splitter didn't work properly when numpy array were provided as an input. Modified `ensure_list` so it doesn't modify an array.

(might need some future work if we allow for "inner splitter" to also have numpy array)

Thanks to @Hoda1394 for reporting!

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by Hoda1394** [comment]
> @Hoda1394 - would you have time to check if this branch works with your example?
@djarecka , Thanks for the fix. I will check it today.

**Comment by Hoda1394** [comment]
@djarecka I tried it and it still gives me the same error despite the length of the two inputs are the same! it runs only when the second variable has the length of one! which is the case that the two variables definitely have not the same shape but there is no complaint from Pydra!
P.S. To elaborate more on the problem, I am using the scaler split over two inputs x and y in a pydra workflow. x is a list of NumPy arrays and y is a list of numbers. they have the same length but I receive this error: "ValueError: Operands wf1.y and wf1.x do not have same shape."

**Comment by effigies** [comment]
Is there a minimal example that could be made into a test case?

**Comment by Hoda1394** [comment]
@effigies I will create one.

**Comment by Hoda1394** [comment]
@djarecka and @effigies, while preparing the test, I found out what was the problem and could fix it with a change in the input. now it works as expected.
Thanks

**Comment by djarecka** [comment]
@satra - added a test for 2d arrays

**Comment by satra** [comment]
thanks - LGTM.

**Pull request merged**
