### PR TITLE
[ENH] Changes to BoshTask

### PR DESCRIPTION
**Pull request by jw-96**
Translating more boutiques specifications to Pydra specs. Checking if output files exist.
## Acknowledgment
- [X] I acknowledge that this contribution will be available under the Apache 2 license.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Summary
Adding support for some more bosh input specifications: support for default values, integer values, and mandatory inputs.
QoL: ```bosh_file``` input can now be a string, and ```zenodo_id``` can now also start with the "zenodo" prefix.

This pull request also changes how output files that do not exist are handled. Currently, the path to where the file is expected is returned regardless of the file existing. The change in this pull request will make it return ```attr.NOTHING``` if the file does not exist. If an output is marked as mandatory and the output file does not exist then an error will be raised. The motivation behind this change is that it is otherwise not immediately evident which files were created. For example, BET generates usually only a subset of the outputs, but the current behavior would show paths for all. 

The tests were updated to take this behaviour into account.
In the process I found that the [test](https://github.com/nipype/pydra/blob/f2106f62b5cd2273ef96a5aab69de94e413d9aed/pydra/engine/tests/test_shelltask.py#L3017) ```test_shell_cmd_outputspec_7d``` has an issue. It intends to test whether the directory named ```test``` has been created at ```resultsDir```. However, Pydra checks if the ```test``` directory was created in its current working directory, i.e., the cache directory. The test never failed because pydra returned the path to where it expected the directory to be and the test only checked if the name of the lowest directory matches.  The change of the pull request now has Pydra return ```attr.NOTHING```. I think this is a bug relating to how absolute paths in ```output_file_template``` are being interpreted. A possible solution could be to add a metadata key akin to boutiques' ```uses-absolute-path```.

Also, BoshTask already used mandatory outputs prior to this pull request. However, hey are not yet part of the [output specifications](https://pydra.readthedocs.io/en/latest/output_spec.html). Should it be added there?

## Checklist

- [X] All tests passing
- [X] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [X] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

### CODE REVIEW

**Comment by satra** [comment]
@jw-96 - do consider moving this into a different repo: `pydra-boutiques`. it would be great if pydra didn't have to be updated when boutiques changes. i think this was in pydra only because of ease, rather than the right place.

**Comment by jw-96** [comment]
@satra I discussed the possibility of moving BoshTask to its own repo with @djarecka. We think it would be a good idea, especially since the Boutiques tests take quite a while. However, this PR also contains some changes that are not in ```BoshTask.py```:
- For non existent files the output is set to ```attr.NOTHING```.
  - This required some minor adjustments to some tests.
- Adding the ```absolute_path``` to the specifications. If set to true, the formatted template will not be added to the ```output_dir``` path. This change enables one to specify a path in ```output_file_template``` to where the output file will be found (This also enabled fixing ```test_shell_cmd_outputspec_7d``` ).

**Comment by satra** [comment]
Sure. Anything that is relevant to pydra itself should stay.

**Comment by djarecka** [comment]
@jw-96 - do you think it would be easy for you to separate the changes to pydra itself (and if possible, some test that do not requires boutiques should be added). In that case we could open a new repo right away, and add boutiques related changes there

**Comment by jw-96** [comment]
@djarecka Yes, it should not be hard to separate them. Should I make a new PR for everything not related to boutiques?

**Comment by djarecka** [comment]
that would be great, thank you!

**Comment by djarecka** [comment]
I've also added you as a member to the organization if you want to start a new repository. If not, we can work on this on Thursday

**Comment by jw-96** [comment]
Ok, thanks. I opened a new pull request. I probably won't have time today to open the new repo, but I can do it on Monday.

**Pull request closed without merging**
