### PR TITLE
fixing is_existing_file, so doesn't have problem with arrays (closes #251)

### LINKED ISSUE #251: error returning numpy arrays with more than one element in workflow output
version: pydra master

the key piece appears to be the fact that a numpy array is being returned with more than 1 element. i.e the error goes away if the output of the function is changed to `np.array([val])` or `np.array([val, val]).tolist()` 

i think this is the same error that @nicolocin ran into.

<details> <summary> error </summary>

```shell
$ python multiout.py 
Traceback (most recent call last):
  File "multiout.py", line 24, in <module>
    sub(runnable=wf)
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/submitter.py", line 57, in __call__
    self.loop.run_until_complete(self.submit_workflow(runnable, rerun=rerun))
  File "/Users/satra/software/miniconda3/envs/mee-voice/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/submitter.py", line 71, in submit_workflow
    await workflow._run(self, rerun=rerun)
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/core.py", line 869, in _run
    save(odir, result=result, task=self)
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/helpers.py", line 117, in save
    result = copyfile_workflow(wf_path=task_path, result=result)
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/helpers.py", line 129, in copyfile_workflow
    new_value = _copyfile_single_value(wf_path=wf_path, value=value)
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/helpers.py", line 138, in _copyfile_single_value
    return [_copyfile_single_value(wf_path, val) for val in value]
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/helpers.py", line 138, in <listcomp>
    return [_copyfile_single_value(wf_path, val) for val in value]
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/helpers.py", line 143, in _copyfile_single_value
    elif is_existing_file(value):
  File "/Users/satra/software/nipy-repo/pydra/pydra/engine/helpers_file.py", line 540, in is_existing_file
    if not f:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
</details>

To replicate run this code
<details> <summary> code </summary>

```python
import numpy as np
import pydra
import typing as ty
import os

@pydra.mark.task
@pydra.mark.annotate({"return": {"b": ty.Any}})
def test_multiout(val):
    return np.array([val, val])

if __name__ == "__main__":
    cache_dir = os.path.join(os.getcwd(), 'cache3')
    wf = pydra.Workflow("", input_spec=['val'], val=[0, 1, 2],
                        cache_dir=cache_dir)
    wf.add(test_multiout(name="mo",
                         val=wf.lzin.val,
                         cache_dir=cache_dir))
    wf.mo.split('val').combine('val')
    wf.set_output([("b", wf.mo.lzout.b)])

    with pydra.Submitter(plugin="cf", n_procs=2) as sub:
        sub(runnable=wf)
    results = wf.result(return_inputs=True)
```
</details>

### PR DESCRIPTION
**Pull request by djarecka**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

fixing is_existing_file, so doesn't have problem with arrays 

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project
(we are using `black`: you can `pip install pre-commit`,
run `pre-commit install` in the `pydra` directory
and `black` will be run automatically with each commit)

## Acknowledgment
- [ ] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by satra** [comment]
i know this was merged, but this raises a warning:

```
/Users/satra/software/nipy-repo/pydra/pydra/engine/helpers_file.py:540: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if value == "":
```

could this be fixed with a proper comparison across possible types of value?

**Comment by nicolocin** [comment]
I noticed that too, but `FutureWarning` [seem to be around since at least 2015](https://github.com/numpy/numpy/issues/6784) so I don't know if it'll ever get implemented

**Comment by satra** [comment]
it usually means that there is another way of doing this. otherwise we would have to explicitly filter the warning (which i generally don't like).

**Comment by djarecka** [comment]
sorry, haven't noticed the warning.

i'm wondering what would be the best way of comparing this. I could check if this is a numpy array, but I'm not sure how many other non-standard python objects could have the same issue. Any idea for smart checks?

**Pull request merged**
