### PR TITLE
Revert "raise error when workflow returns None"

### PR DESCRIPTION
**Pull request by satra**
Reverts nipype/pydra#292

@nicolocin and @djarecka - i'm reverting this change for now. it seems to create a state where complex workflows don't finish. should have looked at more testing before merge.

### CODE REVIEW

**Comment by satra** [comment]
@nicolocin - after this is reverted, please re-open the PR, and let's make sure to consider all places where output is used and make sure we test the consequences of that.

**Comment by satra** [comment]
i won't do this revert right away if we can fix this, but please don't merge anything else and release a version of pydra.

**Comment by nicolocin** [comment]
Ahh I see.  Didn't close the issue so it's still here #290

**Comment by djarecka** [comment]
@satra - should we add a specific test? Do you have one?

**Comment by djarecka** [comment]
@satra - could we close it?

**Pull request closed without merging**
