### PR TITLE
adding a graph class (possible replacement for networkx)

### PR DESCRIPTION
**Pull request by djarecka**
@satra , @mgxd - i've created a simple class for graph that can be sorted. I'm sure it might be more efficient, but it seems to work (see tests). It also has `removing` that removes the node and sort the list again if needed (addresses what we were discussing yesterday, that even if we sort the graph with `nx` at the beginning, we might have to jump over some nodes anyway)

let me know if I should finish this and replace the `nx`, would have to add methods  like `add_node`, `add_edge`, etc. and probably more tests

### CODE REVIEW

**Comment by djarecka** [comment]
@satra  - I've changed the class, so can work for `Workflow`, tell me what you think

**Comment by djarecka** [comment]
@satra - can do it, but i'm curious how do you want to use it in pydra

**Comment by satra** [comment]
it's not urgent, but would be used to optimize which nodes to run. for optimization we will implement a graph scheduler eventually.

**Comment by djarecka** [comment]
@satra still don't see it, but will implement a simple version

**Comment by djarecka** [comment]
@satra , @mgxd - let me know if you want me to merge it to master before the asyncio PR. Some of the feature might be useful in `Submitter` (e.g. `remove_node` with sorting), but I'm ok with merging this later

**Comment by djarecka** [comment]
open a new PR that has already asyncio changes (#66)

**Pull request closed without merging**
