### PR TITLE
Output spec

### LINKED ISSUE #75: functions with multiple values in return statement
If default `out` for output is used (without defining `output_names` - will be in pr) and a function returns two values, only one value is saved. See:

```
@pydra.to_task
def add_vector(x1, y1, x2, y2):
    return (x1 + x2, y1 + y2)

task5 = add_vector(name="add_vect", 
                   x1=[10, 20], y1=[1, 2], x2=[10, 20, 30], y2=[10, 20, 30])
task5.split(splitter=[("x1", "y1"), ("x2", "y2")])
task5(plugin="cf")
task5.result()
```

### PR DESCRIPTION
**Pull request by djarecka**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
closes  #75

## Summary
- some changes to FunctionTask.output_spec and additional tests for using `__annotations__` to specify multiple outputs etc.
**edited**
issue #75 is fixed and multiple values could be return from functions with and without annotation

- also, I was checking one of the test from test_task that is xfailing, it's about the audit. I split the test to two tests, one is passing, but `test_audit_all` is failing with [the pickling error](https://travis-ci.org/djarecka/pydra/jobs/562287591). @satra - do you know how to fix it? 

## Checklist

- [x] All tests passing
- [x] I have added tests to cover my changes
- [x] I have updated documentation (if necessary)
- [x] My code follows the code style of this project 
(we are using `black`: you can `pip install pre-commit`, 
run `pre-commit install` in the `pydra` directory 
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by djarecka** [comment]
@satra - the failing test was in my older pr: https://github.com/nipype/pydra/pull/76/files#diff-871957728874435d337bd031b6bcb53cR266

I didn't add it at the end, because I understand that the annotation should be the default options.

I don't see any option to do it using `to_task`, but I guess we could add an option to `add_task`  and `FunctionTask.__init__`

**Comment by satra** [comment]
@djarecka - that test should still work. the most default option is no annotation.

**Comment by djarecka** [comment]
@satra  - ok, I found what was wrong and fixed it

**Comment by djarecka** [comment]
@satra - regarding you question about annotating an existing function - see [this PR](https://github.com/djarecka/pydra/pull/7). If this is what you had in mind I could finish it

**Comment by djarecka** [comment]
@satra - you didn't comment on the `Audit.ALL` issue, created #98 to not forget

**Pull request merged**
