### PR TITLE
Tutorial Notebooks

### PR DESCRIPTION
**Pull request by djarecka**
## Summary

* Adding notebooks for tutorials:

- [x] intro to task

- [x] intro to task with state

- [x] intro to workflow

- [x] adding to testing

* Small fixes:
     - fixing cache retrieving 

## Checklist

- [x] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [x] My code follows the code style of this project 
(we are using `black`: you can `pip install pre-commit`, 
run `pre-commit install` in the `pydra` directory 
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by djarecka** [comment]
@effigies - do you know what is wrong with this run?
https://travis-ci.org/nipype/pydra/jobs/565290351

**Comment by effigies** [comment]
Unclear, but it looks like it resolved itself with a new commit. I guess we should keep our eyes out and see if it happens again.

**Comment by kaczmarj** [comment]
i get a `RuntimeError` when running `intro_task_splitter_combiner.ipynb`, specifically when running:

```python
@pydra.mark.task
def add_two(x):
    return x + 2

task1 = add_two(x=[1, 2, 3]).split(splitter="x")
task1()
```

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-50b5d13878cb> in <module>
      4 
      5 task1 = add_two(x=[1, 2, 3]).split(splitter="x")
----> 6 task1()

/code/pydra/pydra/engine/core.py in __call__(self, submitter, plugin, **kwargs)
    249         elif self.state:
    250             with Submitter() as sub:
--> 251                 sub(self)
    252         else:
    253             return self._run(**kwargs)

/code/pydra/pydra/engine/submitter.py in __call__(self, runnable, cache_locations)
     40             self.loop.run_until_complete(runnable._run(self))
     41         else:
---> 42             self.loop.run_until_complete(self.submit(runnable, return_task=True))
     43 
     44     def __enter__(self):

~/miniconda3/envs/pydra/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    569         future.add_done_callback(_run_until_complete_cb)
    570         try:
--> 571             self.run_forever()
    572         except:
    573             if new_task and future.done() and not future.cancelled():

~/miniconda3/envs/pydra/lib/python3.7/asyncio/base_events.py in run_forever(self)
    524         self._check_closed()
    525         if self.is_running():
--> 526             raise RuntimeError('This event loop is already running')
    527         if events._get_running_loop() is not None:
    528             raise RuntimeError(

RuntimeError: This event loop is already running
```

i am running pydra `0.0.1+433.gd477909.dirty` (this branch) on debian 10 with python 3.7.3.

**Comment by djarecka** [comment]
you have to downgrade `tornado`, e.g. `tornado==4.5.3`

**Comment by djarecka** [comment]
@effigies - looks like the error does happen regularly, and I believe always in the same two runs:
https://travis-ci.org/djarecka/pydra/builds/565758378?utm_medium=notification&utm_source=email

**Comment by djarecka** [comment]
@satra - could you please take a look and see if you have something that you want me to add to these three intro notebooks. 
In the intro to task I left some place to write more about the `Audit` and I'd ask you for some help.

**Comment by djarecka** [comment]
@effigies @mgxd (and everyone else) - if you have any suggestions please let me know. 

I will definitely create more notebooks with other topics, but not in this PR. You can create an issue if you think about any specific topic/notebook.

Feel free to improve style and English either in this PR or create a new one once this is accepted.

**Comment by djarecka** [comment]
@effigies @mgxd - and this is another interesting travis error to observe...
https://travis-ci.org/djarecka/pydra/jobs/565786274

no clue, what happened

**Comment by satra** [comment]
@djarecka - you'll have to resolve some conflicts based on the SLURM worker changes

**Comment by djarecka** [comment]
@satra @akeshavan - thanks for your feedback. I added your suggestions. 
I will work on Binder!

**Comment by djarecka** [comment]
@satra - mybinder is having issue with building the environment with proper version of `tornado` from our setup. It's ok if I add a simple `requirements.txt`, see here: https://mybinder.org/v2/gh/djarecka/pydra/mybinder_test

I'm not sure if I want to add this extra file to our main repo, but in case I don't solve issue with our setup, we can temporally add a link to binder from my testing branch

**Comment by djarecka** [comment]
@satra @mgxd @effigies - I'll merge it later tonight if you don't stop me

**Comment by effigies** [comment]
Go for it. I haven't had a look yet, but I can submit suggestions as my own pr later, if I have them.

**Comment by djarecka** [comment]
@effigies @satra @mgxd - I've added a file `requirements.txt`. this is only to set mybinder. It looks like mybinder doesn't recognize our requirements structure, but works fine with `requirements.txt`. Let me know if this is an issue.

**Pull request merged**
