### PR TITLE
WIP-Adding software version retrieval 

### PR DESCRIPTION
**Pull request by rcali21**

### CODE REVIEW

**Comment by djarecka** [comment]
@rcali21 - have you seen the errors from the tests. Please let me know if something is not clear from the error messages.

Also, it would be good to expand the tests to check this specific change (after you fix the current tests)

**Comment by rcali21** [comment]
> 

Yes, I will be working on resolving them and building a test, thank you.

**Comment by rcali21** [comment]
@djarecka Please weigh in on this when you see it, thank you.

**Comment by rcali21** [comment]
Would the singularity and SLURM calls be failing because I implemented something that uses stdout?

**Comment by djarecka** [comment]
don't worry about Singularity right now, I think it might be unrelated. Will try to check it locally

**Comment by djarecka** [comment]
@rcali21 - I fixed the issue with SIngularity, you could merge the current master to your branch and the tests should pass

**Comment by djarecka** [comment]
thanks for adding a test, but perhaps you can also add version check to the previous test: `test_audit_task`

**Pull request merged**
