### PR TITLE
tst: increase available nodes in slurm image

### PR DESCRIPTION
**Pull request by mgxd**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Summary

Increases available compute nodes in the slurm docker image from 5 to 40.

## Checklist

- [ ] All tests passing
- [ ] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [ ] My code follows the code style of this project 
(we are using `black`: you can `pip install pre-commit`, 
run `pre-commit install` in the `pydra` directory 
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by satra** [comment]
is this still needed?

**Comment by mgxd** [comment]
this just reflects the version of the image we're pulling (`mgxd/slurm:19.05.1`) and makes the test a bit less flaky.

In the future we should probably shift to building the image and pushing whenever the dockerfile is updated to confirm it matches up to the docker image, but this should be fine for now

**Comment by satra** [comment]
> makes the test a bit less flaky.

what helps make it less flaky?

**Comment by mgxd** [comment]
sacct was occasionally returning `Unknown` for some jobs' "Eligible" times. I'm not 100%, but my guess is this happens when the slurmd / slurmdbd gets overloaded with requests.

**Pull request merged**
